# Generated by Django 4.1.5 on 2023-02-21 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(max_length=2)),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.flight')),
            ],
        ),
    ]
