# Generated by Django 4.1.5 on 2023-02-21 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_flight_number_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.airline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airline',
            name='airline_name',
            field=models.CharField(max_length=255),
        ),
    ]
